name: Bug Report
description: 버그 리포트 템플릿
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: 실제 발생한 동작이나 결과를 구체적으로 작성해주세요.
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What you expected to happen?
      description: 원래 기대했던 정상 동작을 작성해주세요.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce it?
      description: 가능한 한 최소한의 단계로 정확하게 작성해주세요.
    validations:
      required: false

  - type: input
    id: where
    attributes:
      label: What's the environment?
      description: 버그가 발생한 환경의 정보를 입력해주세요(URL/계정정보)
    validations:
      required: true
