name: Bug Report
description: 버그 리포트 템플릿
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        버그를 리포트해주셔서 감사합니다!
  - type: textarea
    id: what-happened
    attributes:
      label: 무슨 일이 발생했나요?
      description: 버그에 대해 설명해주세요.
    validations:
      required: true
